const mockEvents = {
  city: {
    id: 708891,
    city: 'Saskatoon',
    lat: 52.12,
    lon: -106.65,
    state: 'SK',
    country: 'ca',
    zip: 'S7H 0A1',
    member_count: 1270
  },

  events: [
    {
      created: 1557256846000,
      duration: 5400000,
      fee: {
        accepts: 'cash',
        amount: 5,
        currency: 'CAD',
        description: 'per person',
        label: 'Price',
        required: false
      },
      id: 'nbhvxqyzlbbc',
      name: 'Soul Healing Evening',
      rsvp_limit: 10,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1566345600000,
      local_date: '2019-08-20',
      local_time: '19:00',
      updated: 1557256846000,
      utc_offset: -18000000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      venue: {
        id: 25696757,
        name: 'Ellen\'s Whole Body Health',
        lat: 52.15083312988281,
        lon: -106.56902313232422,
        repinned: true,
        address_1: '507 Nelson Rd',
        city: 'Saskatoon',
        country: 'ca',
        localized_country_name: 'Canada',
        zip: 'S7S 1P4',
        state: 'sk'
      },
      group: {
        created: 1491961175000,
        name: 'Saskatoon Abundance Seekers',
        id: 23252209,
        join_mode: 'open',
        lat: 52.119998931884766,
        lon: -106.6500015258789,
        urlname: 'Saskatoon-Abundance-Seekers',
        who: 'Members',
        localized_location: 'Saskatoon, SK',
        state: 'SK',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Central'
      },
      link: 'https://www.meetup.com/Saskatoon-Abundance-Seekers/events/nbhvxqyzlbbc/',
      description: '<p>• What we\'ll do<br/>Meditation, spiritual practice, chanting, sharing and soul dancing</p> <p>• What to bring<br/>Bring water to drink</p> <p>• Important to know<br/>There is a $5.00 fee to participate please bring to event.</p> ',
      how_to_find_us: 'We will be hosting in Ellen\'s Whole Body Health',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1557256846000,
      duration: 5400000,
      fee: {
        accepts: 'cash',
        amount: 5,
        currency: 'CAD',
        description: 'per person',
        label: 'Price',
        required: false
      },
      id: 'nbhvxqyzlbkc',
      name: 'Soul Healing Evening',
      rsvp_limit: 10,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1566950400000,
      local_date: '2019-08-27',
      local_time: '19:00',
      updated: 1557256846000,
      utc_offset: -18000000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 25696757,
        name: 'Ellen\'s Whole Body Health',
        lat: 52.15083312988281,
        lon: -106.56902313232422,
        repinned: true,
        address_1: '507 Nelson Rd',
        city: 'Saskatoon',
        country: 'ca',
        localized_country_name: 'Canada',
        zip: 'S7S 1P4',
        state: 'sk'
      },
      group: {
        created: 1491961175000,
        name: 'Saskatoon Abundance Seekers',
        id: 23252209,
        join_mode: 'open',
        lat: 52.119998931884766,
        lon: -106.6500015258789,
        urlname: 'Saskatoon-Abundance-Seekers',
        who: 'Members',
        localized_location: 'Saskatoon, SK',
        state: 'SK',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Central'
      },
      link: 'https://www.meetup.com/Saskatoon-Abundance-Seekers/events/nbhvxqyzlbkc/',
      description: '<p>• What we\'ll do<br/>Meditation, spiritual practice, chanting, sharing and soul dancing</p> <p>• What to bring<br/>Bring water to drink</p> <p>• Important to know<br/>There is a $5.00 fee to participate please bring to event.</p> ',
      how_to_find_us: 'We will be hosting in Ellen\'s Whole Body Health',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1557256846000,
      duration: 5400000,
      fee: {
        accepts: 'cash',
        amount: 5,
        currency: 'CAD',
        description: 'per person',
        label: 'Price',
        required: false
      },
      id: 'nbhvxqyzmbfb',
      name: 'Soul Healing Evening',
      rsvp_limit: 10,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1567555200000,
      local_date: '2019-09-03',
      local_time: '19:00',
      updated: 1557256846000,
      utc_offset: -18000000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 25696757,
        name: 'Ellen\'s Whole Body Health',
        lat: 52.15083312988281,
        lon: -106.56902313232422,
        repinned: true,
        address_1: '507 Nelson Rd',
        city: 'Saskatoon',
        country: 'ca',
        localized_country_name: 'Canada',
        zip: 'S7S 1P4',
        state: 'sk'
      },
      group: {
        created: 1491961175000,
        name: 'Saskatoon Abundance Seekers',
        id: 23252209,
        join_mode: 'open',
        lat: 52.119998931884766,
        lon: -106.6500015258789,
        urlname: 'Saskatoon-Abundance-Seekers',
        who: 'Members',
        localized_location: 'Saskatoon, SK',
        state: 'SK',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Central'
      },
      link: 'https://www.meetup.com/Saskatoon-Abundance-Seekers/events/nbhvxqyzmbfb/',
      description: '<p>• What we\'ll do<br/>Meditation, spiritual practice, chanting, sharing and soul dancing</p> <p>• What to bring<br/>Bring water to drink</p> <p>• Important to know<br/>There is a $5.00 fee to participate please bring to event.</p> ',
      how_to_find_us: 'We will be hosting in Ellen\'s Whole Body Health',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1565732829000,
      duration: 7200000,
      id: '263980400',
      name: 'Supper at Fat Burger ',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1566343800000,
      local_date: '2019-08-20',
      local_time: '18:30',
      updated: 1565732829000,
      utc_offset: -18000000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 26382591,
        name: 'Fatburger Preston Crossing',
        lat: 52.1467170715332,
        lon: -106.62200164794922,
        repinned: false,
        address_1: '1703 Preston Ave N #110',
        city: 'Saskatoon',
        country: 'ca',
        localized_country_name: 'Canada',
        zip: 'S7N 4V2',
        state: 'SK'
      },
      group: {
        created: 1559257271000,
        name: 'Saskatoon Christian Social Club (20’s and 30’s)',
        id: 32069046,
        join_mode: 'open',
        lat: 52.119998931884766,
        lon: -106.6500015258789,
        urlname: 'Saskatoon-Christian-Social-Club-20-s-and-30-s',
        who: 'Members',
        localized_location: 'Saskatoon, SK',
        state: 'SK',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Central'
      },
      link: 'https://www.meetup.com/Saskatoon-Christian-Social-Club-20-s-and-30-s/events/263980400/',
      description: '<p>Supper at Fat Burger at 6:30pm, a chance to talk and get to know people.</p> ',
      how_to_find_us: 'I will get a table and let everyone know where I am sitting.',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1564544659000,
      duration: 7200000,
      id: '263605817',
      name: 'Mini-golf @ Putt and Bounce',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1566759600000,
      local_date: '2019-08-25',
      local_time: '14:00',
      updated: 1564544667000,
      utc_offset: -18000000,
      waitlist_count: 0,
      yes_rsvp_count: 18,
      venue: {
        id: 24006556,
        name: 'Putt and Bounce',
        lat: 52.119998931884766,
        lon: -106.6500015258789,
        repinned: true,
        address_1: '8th St and Arlington Ave',
        city: 'Saskatoon',
        country: 'ca',
        localized_country_name: 'Canada',
        zip: 'S7H 0A1',
        state: 'SK'
      },
      group: {
        created: 1437107403000,
        name: 'Saskatoon Fun-loving 40-somethings',
        id: 18747442,
        join_mode: 'open',
        lat: 52.119998931884766,
        lon: -106.6500015258789,
        urlname: 'Fun-loving-40s-Saskatoon',
        who: 'Fun-lovers',
        localized_location: 'Saskatoon, SK',
        state: 'SK',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Central'
      },
      link: 'https://www.meetup.com/Fun-loving-40s-Saskatoon/events/263605817/',
      description: '<p>Another opportunity to be outside during the last days of summer. Practice your putting skills...or not. It\'s all fun and games. :)</p> <p>Date: Sunday August 25<br/>Time:200pm<br/>Location: Putt and Bounce (corner of 8th St and Arlington - behind Fuddruckers)</p> <p>A game costs $9.50. Putters and balls supplied.<br/>Meet at the entrance where we pay.</p> <p>Guests welcome.</p> <p>If anyone wants to go to Fuddruckers for dinner/ice cream after our game, we can arrange that for those who want to. It\'s in the same parking lot as putt and bounce.</p> <p>If this is your first meet up with the Fun-Lovers in 2019, please kindly bring $5 (annual fee) to assist in covering the admin costs of the group. Thanks in advance. :)</p> ',
      visibility: 'public',
      member_pay_fee: false
    }
  ]
};
export { mockEvents };
